### PR TITLE
Allow running custom commands using AUTO_NOTIFY_COMMAND

### PR DESCRIPTION
**Pull request by MichaelAquilina**
Questions

- [ ] Security Implications?
- [ ] How would this work with customising text?

### CODE REVIEW

**Comment by psprint** [comment]
I don't see command line instructions at the PR. How to test it?

**Comment by MichaelAquilina** [comment]
Hi @psprint, sorry for how long I took to reply. This PR is very out of date now so it pretty much needs updating again. Will give it another look when I have more time in the next few weeks

**Comment by justrajdeep** [comment]
Hi 
is this implemented ? @MichaelAquilina

**Comment by MichaelAquilina** [comment]
Hi @justrajdeep. No this is not merged into the `master` branch. I've kind of abandoned this PR but feel free to try pick it up and fix it up for your use if you find it useful!

**Pull request closed without merging**
